### ISSUE TITLE
Bestückung einiger Steckverbinder verkehrt orientiert

### ISSUE THREAD

**Issue by ml-hn** [heise/MaXYposi_Grbl_644#1]
Die Bestückung einiger Steckverbinder auf dem Foto "platine_bestückt" ist von der Orientierung her falsch. Betroffen sind folgende: PL4, PL2, PL10, PL204, PL201-PL203, PL204, PL8, PL3 und PL7.
Die Markierungen von Pin 1 an den betroffenen Bauelementen und der Vergleich mit dem Platinen-Layaut und dem Schaltbild verdeutlichen diesen Fehler.
Eine praktische Bedeutung besteht nur bei die Verkabelung mit den externen Komponenten, wodurch mir auch der Fehler auffiel.

Mfg

Michael L.

**Comment by JRoppert** [comment]
Sehe ich nicht so. Wenn ich von platine_bestueckt.JPG ausgehe, dann ist z.B. bei PL2 auf dem Platinenlayout Pin 1 rechts (quadratisches Lötauge), auf meinem Stecker ist auch der passende Pin als "Pin 1" markiert und mit dem Schaltplan passt das auch zusammen.

**Comment by heise** [comment]
Wir haben aus historischen Gründen (PCB-Bauteilbibliothek) "Pin 1 ist links wenn Lasche hinten" angenommen. Bei fertig konfektionierten Kabeln ist aber meist rechts das schwarze Kabel, demzufolge Pin 1. Wer selbst crimpt, hat das Problem nicht.

**Comment by sttts** [comment]
Die großen DIN-Stecker sind auch falsch herum. Ein Versehen?
