### ISSUE TITLE
Code lässt sich ohne Unterstützung der 4. Achse nicht übersetzen

### ISSUE THREAD

**Issue by AndreasCS** [heise/MaXYposi_Grbl_644#4]
Deaktiviert man in der Datei config.h die Unterstützung für die 4-Achse (Auskommentieren der Zeile 693: define AXIS_C_ENABLE), wird der Übersetzungsvorgang mit Fehlern abgebrochen.

In zwei Dateien fehlt die ifdef Abfrage für AXIS_C_ENABLE
Datei motion_control.h: Zeile 34 (Konstante HOMING_CYCLE_C)
Datei system.c: Zeile 189 (Homing single Axis Befehle)

**Comment by heise** [comment]
Behoben mit #1.1f4
