### ISSUE TITLE
Build Info Message uses wrong format

### ISSUE THREAD

**Issue by EtlamGit** [heise/MaXYposi_Grbl_644#6]
According to the [documentation](https://github.com/gnea/grbl/blob/master/doc/markdown/interface.md)

- The first line `[VER:]` contains the build version and date.
- A string may appear after the second `:` colon. It is a stored EEPROM string a user via a `$I=line` command or OEM can place there for personal use or tracking purposes.

But the code here adds another `:` colon together with the word `BUILD`.

Therefore it is not possible to parse the Build Info Message.

Correct code would be `report.c #370`:
```
// Prints build info line
void report_build_info(char *line)
{
  printPgmString(PSTR("[VER:" GRBL_VERSION "." GRBL_VERSION_BUILD ":"));
  printString(line);

```

**Comment by heise** [comment]
Fixed with 1.1f5
